version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
  deploy:
    executor:
      name: node/default
    steps:
      - checkout
      - run:
          name: Deploy to Heroku
          command: |
            curl https://cli-assets.heroku.com/install.sh | sh
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              git push -f https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME_PROD.git master
            fi
workflows:
  build-deploy:
    jobs:
      - build-and-test
      - deploy
